import { StyleSheet } from 'react-native'; 

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
    paddingBottom: 50,
    justifyContent: 'space-between',
  },
  container2: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 10,
    paddingBottom: 50,
    paddingTop: 50,
    justifyContent: 'space-between',
  },
  container3: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 0,  
    position: 'relative',
  }, 
  title: {
    fontSize: 20,     
    fontWeight: 'bold',   
    color: '#000',    
    marginBottom: 10, 
  }, 
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1E874B',
    marginBottom: 4,
    marginTop: 10,
  },
  required: {
    color: 'red',
  },
  mColor: {
    color: '#1E874B'
  },
  input: {
    marginBottom: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1, 
    borderBottomColor: '#1E874B',
    color: 'red',
  },
  button: {
    backgroundColor: '#1E874B',
    borderRadius: 100,
    paddingVertical: 8, 
    marginBottom: 50,
    color: '#ffffff',
  },
  buttonNum: {
    backgroundColor: '#1E874B',
    borderRadius: 100,
    paddingVertical: 8, 
    marginBottom: 50,
    color: '#ffffff',
  },
  buttonLabel: {
    color: '#ffffff',
    fontSize: 16,
  },
  buttonLabel2: {
    color: '#1E874B',
    fontSize: 16,
  },
  card: {
    borderRadius: 16,
    elevation: 3,
    backgroundColor: '#fff',
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  view: {
     
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    marginTop: 40,
  },
  viewBell: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: 'red',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  buttonLabel1: {
    fontSize: 16, 
    fontWeight: "bold", 
    color: "#FFFFFF"
  },
  buttonLabel2: {
    fontSize: 16, 
    fontWeight: "bold", 
    color: "#1E874B",
  },
  TextMal: {
    fontSize: 12, 
    color: '#888', 
    marginTop: 4, 
    textAlign: 'center',
  },
  BtnUpload: {
    width: '100%',                
    borderColor: '#1E874B',
    borderWidth: 1,
    borderRadius: 8,
    borderStyle: 'dashed',
    paddingVertical: 10,
  },
  ImgBank: {
    width: '100%', 
    height: 300, 
    marginRight: 16, 
    alignSelf: 'center',  
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10
  },
  TextBankDes: {
    fontSize: 12, 
    color: '#555', 
    marginBottom: 4
  },
  BgWhite: {
    backgroundColor: '#fff',
    color: "#1E874B",
  },
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#fff",
  },
  dayBlock: {
    marginBottom: 16,
    borderBottomWidth: 0.5,
    borderColor: "#000",
    paddingBottom: 10,
    color: '#000', 
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dayText: {
    fontSize: 16,
    fontWeight: "600",
    color: '#000', 
  },
  closeText: {
    fontSize: 14, 
    color: '#000', 
  },
  slotRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    color: '#000', 
  },
  timeButton: {
    borderRadius: 10,
    minWidth: 90,
  },
  addBtn: {
    alignSelf: "flex-start",
    marginTop: 6,
    color: '#000',  
  },
  saveButton: {
    marginTop: 20,
    borderRadius: 30,
    paddingVertical: 8,
  },
  titleFood: {
    fontSize: 20,     
    fontWeight: 'bold',   
    color: '#000',    
    marginBottom: 10, 
    marginLeft: 10,
  }, 
  buttonNumFood: {
    backgroundColor: '#1E874B',
    borderRadius: 100,
    paddingVertical: 8, 
    marginBottom: 10,
    color: '#ffffff',
  }, 
  viewCardFo: {
    flexDirection: 'row', 
    marginTop: 10, 
  }, 
  mCard: {
    width: 200, 
    marginRight: 10 , 
    backgroundColor: 'white' , 
    borderWidth: 0, 
    marginBottom: 10,
    marginTop: 10,
    shadowColor: 'transparent'
  }, 
  foodTextMal: {
    fontSize: 12, 
    color: '#888', 
    marginTop: 4,  
  },
  titleMfood: {
    fontSize: 22,     
    fontWeight: 'bold',   
    color: '#000',    
    marginBottom: 10, 
    paddingTop: 20,
    marginTop: 20, 
    marginLeft: 10, 
  }, 
  subMfood: {
    fontSize: 18,     
    fontWeight: 'bold',   
    color: '#000',    
    marginBottom: 10, 
    marginTop: 10, 
    marginLeft: 10,
  }, 
  btnCheck: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    marginBottom: 20,
    backgroundColor: "#1E874B",
    borderRadius: 30,  
    padding: 0,
    marginLeft: 15,
    marginRight: 15, 
  },  
  content: { flex: 1, padding: 16  },
  sectionTitle: { marginBottom: 8, color:"black", fontSize: 20, fontWeight:"bold" }, 
  cardContent: { flexDirection: 'row', alignItems: 'center', marginBottom: 20, paddingBottom: 0 },
  thumb: { width: 64, height: 64, borderRadius: 8, marginRight: 12 },
  muted: { color: '#666' },
  edit: { color: '#ff0000', marginTop: 4 },
  qtyBox: { alignItems: 'flex-end' },
  qtyRow: { flexDirection: 'row', alignItems: 'center' },
  price: { fontWeight: '700' },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  greenHint: { color: '#1E874B', marginTop: 8 },
  envRow: { flexDirection: 'row', alignItems: 'center' },
  pickRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  addressWarning: { marginTop: 12, color: '#666' },
  footer: { padding: 12, borderTopLeftRadius: 16, borderTopRightRadius: 16 , marginLeft: 10 , marginRight: 10, padding: 15 , paddingBottom: 30 },
  footerInner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  orderBtn: { minWidth: 150 },
  addressRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 0 , color: '#1E874B' },
  optionRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 0 },
  optionText: { color: '#546E7A' },
  labelAdd: { color: '#546E7A', marginRight: 8 },
  address: { flex: 1, color: '#1E874B', fontWeight: '500' , fontWeight:"bold" },
  titleMedium: { flex: 1, color: '#1E874B', fontWeight: '500' , fontWeight:"bold" },
  minus: { color: '#1E874B', fontWeight: '500' , fontWeight:"bold" },
  plus: { color: '#1E874B', fontWeight: '500' , fontWeight:"bold" },
  quantity: { color: '#1E874B', fontWeight: '500' , fontWeight:"bold" },
  subPrice: {
    fontSize: 16, 
    color: '#000000', 
    marginTop: 4,  
    fontWeight:"bold"
  },    
  paymentRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 0 },
  modal: { backgroundColor: 'white', padding: 20, borderTopLeftRadius: 16, borderTopRightRadius: 16  },
  modalTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16 , color: '#000000'},


   
  modalPay: { justifyContent: 'flex-end', margin: 0 },
  sheet: {
    backgroundColor: 'white',
    padding: 20,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  handle: {
    width: 40,
    height: 5,
    backgroundColor: '#ccc',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16 , color: '#000000' },
  orderBtn: {
    minWidth: 150,
    borderRadius: 25,    
    paddingVertical: 6,  
  },
  bthtx: {
    fontWeight: "bold",
    fontSize: 30,
    marginTop: 10
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  historyLink: {
    color: '#1e88e5', // น้ำเงินเหมือนลิงก์
    fontSize: 14,
  },

});

